<a href="https://colab.research.google.com/github/SattGamer/DeepLearning/blob/main/Redes_Neuronales_b%C3%A1sicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Redes neuronales básicas (Python y Numpy)


**Estudiante:** Over Santiago Grosso Pérez  

**Actividad:** Redes Neuronales Básicas  

**Link Github:** https://github.com/SattGamer/DeepLearning/blob/main/Redes_Neuronales_b%C3%A1sicas.ipynb

##Perceptrón Básico
El perceptrón es la neurona artificial más simple.

**Fórmula**
  
  **Y=f(XW+B)**
  
Donde:

1. X = Entradas

2. W = Pesos

3. B = Sesgo (Bias)

4. f = Función de activación

In [3]:
# ==========================================
# PERCEPTRÓN SIMPLE
# ==========================================
import numpy as np

# Entradas
X = np.array([1, 0])

# Pesos
W = np.array([0.8, 0.2])

# Bias
B = -0.5

# Suma ponderada
Z = np.dot(X, W) + B


'''
La función escalón es la función de activación
más simple que existe en una red neuronal.
Su trabajo es tomar un valor numérico y convertirlo
en una decisión de tipo sí o no, verdadero o falso, 1 o 0.
'''
def escalon(x):
    if x >= 0:
        return 1
    return 0

# Resultado
Y = escalon(Z)

print("Resultado:", Y)

Resultado: 1


###Red Neuronal de Una Capa

In [8]:
# ==============================
# RED NEURONAL DE UNA CAPA
# ==============================
import numpy as np

# ------------------------------------------------------------
# 1. DATOS DE ENTRADA
# ------------------------------------------------------------
# Creamos una matriz con cuatro ejemplos de entrada.
# Cada fila representa un ejemplo y cada columna una característica.
# Ejemplo 1: [0, 0]
# Ejemplo 2: [0, 1]
# Ejemplo 3: [1, 0]
# Ejemplo 4: [1, 1]
#
# La matriz tiene una dimensión de 4 filas y 2 columnas:

Matriz_X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# 2. INICIALIZACIÓN DE LOS PESOS


# Establecemos una semilla para que Numpy genere siempre
# los mismos números aleatorios cada vez que ejecutemos el código.
# Esto facilita repetir y revisar los resultados.

np.random.seed(42)

# Generamos los pesos iniciales de la neurona.

#
# Se crean 2 pesos porque cada ejemplo tiene 2 características.
# Se utiliza 1 columna porque la red tiene una sola neurona de salida.

#
# W tendrá una dimensión de 2 filas y 1 columna:

#
# W = [[peso para la primera característica],
#      [peso para la segunda característica]]
W = np.random.rand(2, 1)

# 3. INICIALIZACIÓN DEL BIAS O SESGO


# Creamos un valor aleatorio para el bias.

#
# El bias es un valor adicional que se suma al resultado de la
# multiplicación entre las entradas y los pesos.

#
# Su función es ayudar a la neurona a ajustar su respuesta,
# incluso cuando todos los valores de entrada son cero.

B = np.random.rand(1)



# 4. FUNCIÓN DE ACTIVACIÓN SIGMOIDE

# La función sigmoide convierte cualquier número en un valor
# comprendido entre 0 y 1.
# Un resultado cercano a 0 puede interpretarse como 0.
# Un resultado cercano a 1 puede interpretarse como 1.

def sigmoid(Matriz_X):
    return 1 / (1 + np.exp(-Matriz_X))


# 5. CÁLCULO DE LA SUMA PONDERADA
# Multiplicamos la matriz de entradas Matriz_X por la matriz de pesos W.
# Después, sumamos el bias B.
#
# La fórmula matemática es:
# Z = (X · W) + B
#
# np.dot(X, W) realiza la multiplicación matricial.
# El resultado Z contiene un valor para cada ejemplo de entrada.

Z = np.dot(Matriz_X, W) + B

# 6. GENERACIÓN DE LAS PREDICCIONES


# Aplicamos la función sigmoide a cada valor de Z.
# Esto convierte los resultados en valores entre 0 y 1,
# que representan la salida de la red neuronal.

Y = sigmoid(Z)


# 7.RESULTADOS

# Mostramos los pesos utilizados por la neurona.
print("Pesos:")
print(W)


# \n agrega un salto de línea antes de mostrar el bias.
print("\nBias:")
print(B)


# Mostramos la suma ponderada antes de aplicar la sigmoide.
print("\nSuma ponderada:")
print(Z)


# Mostramos las predicciones finales de la red.
print("\nPredicciones:")
print(Y)

Pesos:
[[0.37454012]
 [0.95071431]]

Bias:
[0.73199394]

Suma ponderada:
[[0.73199394]
 [1.68270825]
 [1.10653406]
 [2.05724837]]

Predicciones:
[[0.67524268]
 [0.84326281]
 [0.75148239]
 [0.88667798]]


##Red Neuronal Multicapa (Vainilla)


In [9]:


import numpy as np

# 1. DATOS DE ENTRADA

# Cada fila representa un ejemplo.
# Cada columna representa una característica.

# La matriz tiene:
# - 4 ejemplos.
# - 2 características por ejemplo.

Matriz_X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]

])

# 2. CONFIGURACIÓN DE LA RED NEURONAL

# Obtenemos automáticamente la cantidad de características
# que tiene cada ejemplo de entrada.
# En este caso, Matriz_X tiene 2 columnas, por lo tanto,
# la red recibe 2 características de entrada.

numero_entradas = Matriz_X.shape[1]


# Definimos la cantidad de neuronas que tendrá la capa oculta.
# En este ejercicio utilizaremos 3 neuronas como ejemplo.
# Esta cantidad es una decisión de diseño y podría cambiarse
# según el problema que se quiera resolver.

numero_neuronas_ocultas = 3


# Definimos la cantidad de neuronas de salida.
# Utilizamos una neurona porque queremos obtener
# una sola predicción para cada ejemplo.

numero_salidas = 1



# 3. SEMILLA (Seed) PARA GENERAR NÚMEROS ALEATORIOS
# La semilla permite obtener los mismos números aleatorios
# cada vez que ejecutamos el código.
#
# Esto facilita repetir el ejercicio y comparar los resultados.
np.random.seed(42)


# 4. PESOS ENTRE LA ENTRADA Y LA CAPA OCULTA
# Creamos los pesos que conectan las características(Columnas) de entrada
# con las neuronas de la capa oculta.
#
# En este ejemplo, la matriz W1 tiene:
# - Una fila por cada característica de entrada.
# - Una columna por cada neurona de la capa oculta.
# Dimensión resultante: 2 filas y 3 columnas.

W1 = np.random.rand(
    numero_entradas,
    numero_neuronas_ocultas
)



# 5. BIAS DE LA CAPA OCULTA
# Creamos un valor de bias para cada neurona de la capa oculta.

# Como configuramos 3 neuronas ocultas, se generan 3 valores.
# Si cambiamos la cantidad de neuronas, la cantidad de bias
# también cambiará automáticamente.
#
# Dimensión resultante: 1 fila y 3 columnas.
B1 = np.random.rand(
    1,
    numero_neuronas_ocultas
)



# 6. PESOS ENTRE LA CAPA OCULTA Y LA CAPA DE SALIDA
# Creamos los pesos que conectan las neuronas de la capa oculta
# con la neurona de salida.
#
# La matriz W2 tiene:
# - Una fila por cada neurona de la capa oculta.
# - Una columna por cada neurona de salida.
#
# Dimensión resultante: 3 filas y 1 columna.
W2 = np.random.rand(
    numero_neuronas_ocultas,
    numero_salidas
)

# 7. BIAS DE LA CAPA DE SALIDA
# Creamos un valor de bias para cada neurona de salida.
#
# Como configuramos una neurona de salida,
# se genera un único valor de bias.
#
# Dimensión resultante: 1 fila y 1 columna.
B2 = np.random.rand(
    1,
    numero_salidas
)




# 8. FUNCIÓN DE ACTIVACIÓN SIGMOIDE
# La función sigmoide recibe una matriz de valores y transforma
# cada uno de ellos en un número comprendido entre 0 y 1.
#
# Fórmula:
# sigmoide(x) = 1 / (1 + e^(-x))
#
# Los resultados pueden interpretarse así:
# - Un valor cercano a 0 indica menor activación.
# - Un valor cercano a 1 indica mayor activación.

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# ============================================================
# PROCESAMIENTO DE LA CAPA OCULTA
# 9. SUMA PONDERADA DE LA CAPA OCULTA

# Multiplicamos los datos de entrada por los pesos W1
# y sumamos los bias B1.
#
# Fórmula:
# Z1 = (Matriz_X · W1) + B1
#
# Dimensiones:
# Matriz_X = 4 x 2
# W1       = 2 x 3
# B1       = 1 x 3
# Z1       = 4 x 3
#
# El resultado contiene, para cada ejemplo, un valor calculado
# por cada neurona de la capa oculta.
Z1 = np.dot(Matriz_X, W1) + B1


# 10. ACTIVACIÓN DE LA CAPA OCULTA
# Aplicamos la función sigmoide a todos los valores de Z1.
#
# A1 almacena las salidas activadas de la capa oculta.
# Estas salidas se utilizarán como entradas de la capa siguiente.
A1 = sigmoid(Z1)




# ============================================================
# PROCESAMIENTO DE LA CAPA DE SALIDA
# ============================================================


# 11. SUMA PONDERADA DE LA CAPA DE SALIDA
# Multiplicamos las salidas de la capa oculta por los pesos W2
# y sumamos el bias B2.
#
# Fórmula:
# Z2 = (A1 · W2) + B2
#
# Dimensiones:
# A1 = 4 x 3
# W2 = 3 x 1
# B2 = 1 x 1
# Z2 = 4 x 1
#
# El resultado contiene un valor para cada ejemplo procesado.
Z2 = np.dot(A1, W2) + B2


# 12. PREDICCIÓN FINAL
# Aplicamos nuevamente la función sigmoide.
Y = sigmoid(Z2)



# 13. MOSTRAR LA CONFIGURACIÓN DE LA RED
print("Número de características de entrada:")
print(numero_entradas)

print("\nNúmero de neuronas ocultas:")
print(numero_neuronas_ocultas)

print("\nNúmero de neuronas de salida:")
print(numero_salidas)
print("\n==================================================================")

# 14. MOSTRAR LOS RESULTADOS DE LA CAPA OCULTA

print("\nPesos de la entrada a la capa oculta:")
print(W1)

print("\nBias de la capa oculta:")
print(B1)

print("\nSuma ponderada de la capa oculta:")
print(Z1)

print("\nSalidas activadas de la capa oculta:")
print(A1)
print("\n==================================================================")


# 15. MOSTRAR LOS RESULTADOS DE LA CAPA DE SALIDA


print("\nPesos de la capa oculta a la capa de salida:")
print(W2)

print("\nBias de la capa de salida:")
print(B2)

print("\nSuma ponderada de la capa de salida:")
print(Z2)

print("\nPredicciones finales de la red:")
print(Y)
print("\n==================================================================")

Número de características de entrada:
2

Número de neuronas ocultas:
3

Número de neuronas de salida:
1


Pesos de la entrada a la capa oculta:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

Bias de la capa oculta:
[[0.05808361 0.86617615 0.60111501]]

Suma ponderada de la capa oculta:
[[0.05808361 0.86617615 0.60111501]
 [0.6567421  1.02219479 0.75710953]
 [0.43262373 1.81689045 1.33310895]
 [1.03128222 1.97290909 1.48910347]]

Salidas activadas de la capa oculta:
[[0.51451682 0.70394941 0.64591136]
 [0.65852817 0.7353999  0.68072585]
 [0.60650002 0.86019259 0.79135443]
 [0.7371644  0.87792324 0.81594367]]


Pesos de la capa oculta a la capa de salida:
[[0.70807258]
 [0.02058449]
 [0.96990985]]

Bias de la capa de salida:
[[0.83244264]]

Suma ponderada de la capa de salida:
[[1.83772413]
 [1.97410892]
 [2.04713776]
 [2.16387195]]

Predicciones finales de la red:
[[0.86267932]
 [0.87805177]
 [0.88565809]
 [0.89695796]]

